#!/bin/sh
#---------------------------
# Testing strongswan-starter
#---------------------------
CMDS="
/usr/bin/pki
/usr/lib/ipsec/_copyright
/usr/lib/ipsec/scepclient
/usr/lib/ipsec/stroke
/usr/sbin/ipsec
"

for cmd in $CMDS; do
	$cmd --help > /dev/null 2>&1
	RET=$?

	if [ $RET -ne 0 ]; then
	  echo "ERROR, failed to run ${cmd}" >&2
	  exit $RET
	fi
done
