#!/bin/sh
#------------------------
# Testing starter, charon
#------------------------
DAEMONS="starter charon"

for daemon in $DAEMONS; do
    if pidof -x $daemon > /dev/null; then
        echo "$daemon OK"
    else
        echo "ERROR: ${daemon} IS NOT RUNNING"
        exit 1
    fi
done
